import { Router } from "express";
import aiAskRouter from "./ai/ask.js";
import appWebhookRouter from "./app-webhook/receive.js";
import auditRouter from "./policy/audit.js";
import botsRouter from "./routing/bots.js";
import botServersRouter from "./routing/bot-servers.js";
import byoBotLinkRouter from "./byo-bot/link.js";
import byoBotReassignLinkerRouter from "./byo-bot/reassign-linker.js";
import byoBotRevokeRouter from "./byo-bot/revoke.js";
import byoBotStatusRouter from "./byo-bot/status.js";
import byoBotStreamRouter from "./byo-bot/stream.js";
import byoBotVerifyRouter from "./byo-bot/verify.js";
import membersListRouter from "./members/list.js";
import membersStreamRouter from "./members/stream.js";
import membersSetNicknameRouter from "./members/identity/set-nickname.js";
import membersAddRoleRouter from "./members/roles/add-role.js";
import membersRemoveRoleRouter from "./members/roles/remove-role.js";
import membersTimeoutRouter from "./members/moderation/timeout.js";
import membersKickRouter from "./members/moderation/kick.js";
import membersBanRouter from "./members/moderation/ban.js";
import membersUnbanRouter from "./members/moderation/unban.js";
import webhooksCreateRouter from "./webhooks/create.js";
import webhooksUpdateRouter from "./webhooks/update.js";
import webhooksDeleteRouter from "./webhooks/delete.js";
import webhooksListRouter from "./webhooks/list.js";
import webhooksStreamRouter from "./webhooks/stream.js";
import stateWebhooksSyncRouter from "./state/webhooks-sync.js";
import stateWebhooksUpsertRouter from "./state/webhooks-upsert.js";
import stateWebhooksDeleteRouter from "./state/webhooks-delete.js";
import serverEmojisCreateRouter from "./server-emojis/create.js";
import serverEmojisUpdateRouter from "./server-emojis/update.js";
import serverEmojisDeleteRouter from "./server-emojis/delete.js";
import serverEmojisListRouter from "./server-emojis/list.js";
import serverEmojisStreamRouter from "./server-emojis/stream.js";
import stateServerEmojisSyncRouter from "./state/server-emojis-sync.js";
import stateServerEmojisUpsertRouter from "./state/server-emojis-upsert.js";
import stateServerEmojisDeleteRouter from "./state/server-emojis-delete.js";
import serverStickersCreateRouter from "./server-stickers/create.js";
import serverStickersUpdateRouter from "./server-stickers/update.js";
import serverStickersDeleteRouter from "./server-stickers/delete.js";
import serverStickersListRouter from "./server-stickers/list.js";
import serverStickersStreamRouter from "./server-stickers/stream.js";
import stateServerStickersSyncRouter from "./state/server-stickers-sync.js";
import stateServerStickersUpsertRouter from "./state/server-stickers-upsert.js";
import stateServerStickersDeleteRouter from "./state/server-stickers-delete.js";
import guildSettingsGetRouter from "./guild-settings/get.js";
import guildSettingsStreamRouter from "./guild-settings/stream.js";
import guildSettingsSetNameRouter from "./guild-settings/identity/set-name.js";
import guildSettingsSetIconRouter from "./guild-settings/identity/set-icon.js";
import guildSettingsSetBannerRouter from "./guild-settings/identity/set-banner.js";
import guildSettingsSetDescriptionRouter from "./guild-settings/identity/set-description.js";
import guildSettingsSetSystemChannelRouter from "./guild-settings/structure/set-system-channel.js";
import guildSettingsSetAfkRouter from "./guild-settings/structure/set-afk.js";
import guildSettingsSetWelcomeScreenRouter from "./guild-settings/access/set-welcome-screen.js";
import guildSettingsSetVerificationLevelRouter from "./guild-settings/access/set-verification-level.js";
import stateGuildSettingsUpsertRouter from "./state/guild-settings-upsert.js";
import channelsDeletePermissionsRouter from "./channels/delete-permissions.js";
import channelOverwritesListRouter from "./channel-overwrites/list.js";
import channelOverwritesStreamRouter from "./channel-overwrites/stream.js";
import stateChannelOverwritesSyncRouter from "./state/channel-overwrites-sync.js";
import clansListServersRouter from "./clans/list-servers.js";
import clansRemoveServerRouter from "./clans/remove-server.js";
import clansServersStreamRouter from "./clans/servers-stream.js";
import emojisListRouter from "./emojis/list.js";
import emojisSyncRouter from "./emojis/sync.js";
import interactionsCleanupRouter from "./interactions/cleanup.js";
import interactionsUpsertRouter from "./interactions/upsert.js";
import channelsCreateRouter from "./channels/create.js";
import channelsDeleteRouter from "./channels/delete.js";
import channelsListRouter from "./channels/list.js";
import channelsPermissionsRouter from "./channels/permissions.js";
import channelsStreamRouter from "./channels/stream.js";
import channelsUpdateRouter from "./channels/update.js";
import outboundListRouter from "./outbound/list.js";
import outboundStreamRouter from "./outbound/stream.js";
import outboundTransitionRouter from "./outbound/transition.js";
import presenceRouter from "./presence/get.js";
import publishQueueListRouter from "./publish-queue/list.js";
import publishQueueStreamRouter from "./publish-queue/stream.js";
import publishQueueTransitionRouter from "./publish-queue/transition.js";
import rateLimitRouter from "./policy/rate-limit.js";
import rolesCreateRouter from "./roles/create.js";
import rolesDeleteRouter from "./roles/delete.js";
import rolesListRouter from "./roles/list.js";
import rolesSetPermissionsRouter from "./roles/set-permissions.js";
import rolesSetPositionRouter from "./roles/set-position.js";
import rolesStreamRouter from "./roles/stream.js";
import rolesUpdateRouter from "./roles/update.js";
import serversRouter from "./routing/servers.js";
import stateChannelsSyncRouter from "./state/channels-sync.js";
import stateChannelsUpsertRouter from "./state/channels-upsert.js";
import stateChannelsDeleteRouter from "./state/channels-delete.js";
import stateRolesSyncRouter from "./state/roles-sync.js";
import stateRolesUpsertRouter from "./state/roles-upsert.js";
import stateRolesDeleteRouter from "./state/roles-delete.js";
import stateMembersSyncRouter from "./state/members-sync.js";
import stateMembersUpsertRouter from "./state/members-upsert.js";
import stateMembersDeleteRouter from "./state/members-delete.js";
import stateServerFeaturesRouter from "./state/servers/features.js";
import userPermissionsRouter from "./policy/user-permissions.js";

const router: Router = Router();
router.use("/bots", botsRouter);
router.use("/bots", botServersRouter);
router.use("/byo-bot", byoBotVerifyRouter);
router.use("/byo-bot", byoBotLinkRouter);
router.use("/byo-bot", byoBotRevokeRouter);
router.use("/byo-bot", byoBotStatusRouter);
router.use("/byo-bot", byoBotStreamRouter);
router.use("/byo-bot", byoBotReassignLinkerRouter);
router.use("/members", membersListRouter);
router.use("/members", membersStreamRouter);
router.use("/members", membersSetNicknameRouter);
router.use("/members", membersAddRoleRouter);
router.use("/members", membersRemoveRoleRouter);
router.use("/members", membersTimeoutRouter);
router.use("/members", membersKickRouter);
router.use("/members", membersBanRouter);
router.use("/members", membersUnbanRouter);
router.use("/webhooks", webhooksCreateRouter);
router.use("/webhooks", webhooksUpdateRouter);
router.use("/webhooks", webhooksDeleteRouter);
router.use("/webhooks", webhooksListRouter);
router.use("/webhooks", webhooksStreamRouter);
router.use("/state", stateWebhooksSyncRouter);
router.use("/state", stateWebhooksUpsertRouter);
router.use("/state", stateWebhooksDeleteRouter);
router.use("/server-emojis", serverEmojisCreateRouter);
router.use("/server-emojis", serverEmojisUpdateRouter);
router.use("/server-emojis", serverEmojisDeleteRouter);
router.use("/server-emojis", serverEmojisListRouter);
router.use("/server-emojis", serverEmojisStreamRouter);
router.use("/state", stateServerEmojisSyncRouter);
router.use("/state", stateServerEmojisUpsertRouter);
router.use("/state", stateServerEmojisDeleteRouter);
router.use("/server-stickers", serverStickersCreateRouter);
router.use("/server-stickers", serverStickersUpdateRouter);
router.use("/server-stickers", serverStickersDeleteRouter);
router.use("/server-stickers", serverStickersListRouter);
router.use("/server-stickers", serverStickersStreamRouter);
router.use("/state", stateServerStickersSyncRouter);
router.use("/state", stateServerStickersUpsertRouter);
router.use("/state", stateServerStickersDeleteRouter);
router.use("/guild-settings", guildSettingsGetRouter);
router.use("/guild-settings", guildSettingsStreamRouter);
router.use("/guild-settings", guildSettingsSetNameRouter);
router.use("/guild-settings", guildSettingsSetIconRouter);
router.use("/guild-settings", guildSettingsSetBannerRouter);
router.use("/guild-settings", guildSettingsSetDescriptionRouter);
router.use("/guild-settings", guildSettingsSetSystemChannelRouter);
router.use("/guild-settings", guildSettingsSetAfkRouter);
router.use("/guild-settings", guildSettingsSetWelcomeScreenRouter);
router.use("/guild-settings", guildSettingsSetVerificationLevelRouter);
router.use("/state", stateGuildSettingsUpsertRouter);
router.use("/servers", serversRouter);
router.use("/clans", clansListServersRouter);
router.use("/clans", clansRemoveServerRouter);
router.use("/clans", clansServersStreamRouter);
router.use("/permissions", userPermissionsRouter);
router.use("/rate-limit", rateLimitRouter);
router.use("/audit", auditRouter);
router.use("/ai", aiAskRouter);
router.use("/presence", presenceRouter);
router.use("/outbound", outboundStreamRouter);
router.use("/outbound", outboundTransitionRouter);
router.use("/outbound", outboundListRouter);
router.use("/publish-queue", publishQueueStreamRouter);
router.use("/publish-queue", publishQueueTransitionRouter);
router.use("/publish-queue", publishQueueListRouter);
router.use("/channels", channelsCreateRouter);
router.use("/channels", channelsUpdateRouter);
router.use("/channels", channelsDeleteRouter);
router.use("/channels", channelsPermissionsRouter);
router.use("/channels", channelsDeletePermissionsRouter);
router.use("/channels", channelsListRouter);
router.use("/channels", channelsStreamRouter);
router.use("/channel-overwrites", channelOverwritesListRouter);
router.use("/channel-overwrites", channelOverwritesStreamRouter);
router.use("/state", stateChannelOverwritesSyncRouter);
router.use("/roles", rolesCreateRouter);
router.use("/roles", rolesUpdateRouter);
router.use("/roles", rolesDeleteRouter);
router.use("/roles", rolesSetPositionRouter);
router.use("/roles", rolesSetPermissionsRouter);
router.use("/roles", rolesListRouter);
router.use("/roles", rolesStreamRouter);
router.use("/state", stateChannelsSyncRouter);
router.use("/state", stateChannelsUpsertRouter);
router.use("/state", stateChannelsDeleteRouter);
router.use("/state", stateRolesSyncRouter);
router.use("/state", stateRolesUpsertRouter);
router.use("/state", stateRolesDeleteRouter);
router.use("/state", stateMembersSyncRouter);
router.use("/state", stateMembersUpsertRouter);
router.use("/state", stateMembersDeleteRouter);
router.use("/state", stateServerFeaturesRouter);
router.use("/interactions", interactionsCleanupRouter);
router.use("/interactions", interactionsUpsertRouter);
router.use("/app-webhook", appWebhookRouter);
router.use("/emojis", emojisSyncRouter);
router.use("/emojis", emojisListRouter);

export default router;
